import frappe
def execute():
    workflow_dict = {"name":"Stock Transfer Process",
    "workflow_name":"Stock Transfer Process",
    "document_type":"Stock Entry",
    "is_active":1,
    "override_status":0,
    "send_email_alert":0,
    "workflow_state_field":"workflow_state",
    "doctype":"Workflow",
    "states":[{
    "state":"Saved",
    "doc_status":"0",
    "update_field":None,
    "update_value":None,
    "is_optional_state":0,
    "avoid_status_override":1,
    "next_action_email_template":None,
    "allow_edit":"All",
    "send_email":0,
    "message":None,
    "workflow_builder_id":"1",
    "parent":"Stock Transfer Process",
    "parentfield":"states",
    "parenttype":"Workflow",
    "doctype":"Workflow Document State"},
    {"state":"Pending Submission",
    "doc_status":"0",
    "update_field":None,
    "update_value":None,
    "is_optional_state":0,
    "avoid_status_override":0,
    "next_action_email_template":None,
    "allow_edit":"System Manager",
    "send_email":0,
    "message":None,
    "workflow_builder_id":"2",
    "parent":"Stock Transfer Process",
    "parentfield":"states",
    "parenttype":"Workflow",
    "doctype":"Workflow Document State"},
    {
    "state":"Rejected Submission",
    "doc_status":"0",
    "update_field":None,
    "update_value":None,
    "is_optional_state":0,
    "avoid_status_override":0,
    "next_action_email_template":None,
    "allow_edit":"System Manager",
    "send_email":0,
    "message":None,
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"states",
    "parenttype":"Workflow",
    "doctype":"Workflow Document State"},
    {
    "state":"Posted",
    "doc_status":"1",
    "update_field":None,
    "update_value":None,
    "is_optional_state":0,
    "avoid_status_override":1,
    "next_action_email_template":None,
    "allow_edit":"System Manager",
    "send_email":0,
    "message":None,
    "workflow_builder_id":"4",
    "parent":"Stock Transfer Process",
    "parentfield":"states",
    "parenttype":"Workflow",
    "doctype":"Workflow Document State"},
    {"state":"Pending Cancellation",
    "doc_status":"1",
    "update_field":None,
    "update_value":None,
    "is_optional_state":0,
    "avoid_status_override":0,
    "next_action_email_template":None,
    "allow_edit":"System Manager",
    "send_email":0,
    "message":None,
    "workflow_builder_id":"5",
    "parent":"Stock Transfer Process",
    "parentfield":"states",
    "parenttype":"Workflow",
    "doctype":"Workflow Document State"},
    {
    "state":"Rejected Cancellation",
    "doc_status":"1",
    "update_field":None,
    "update_value":None,
    "is_optional_state":0,
    "avoid_status_override":0,
    "next_action_email_template":None,
    "allow_edit":"System Manager",
    "send_email":0,
    "message":None,
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"states",
    "parenttype":"Workflow",
    "doctype":"Workflow Document State"},
    {"state":"Discarded",
    "doc_status":"2",
    "update_field":None,
    "update_value":None,
    "is_optional_state":0,
    "avoid_status_override":1,
    "next_action_email_template":None,
    "allow_edit":"System Manager",
    "send_email":0,
    "message":None,
    "workflow_builder_id":"6",
    "parent":"Stock Transfer Process",
    "parentfield":"states",
    "parenttype":"Workflow",
    "doctype":"Workflow Document State"}],
    "transitions":[{
    "state":"Saved",
    "action":"Submit for Review",
    "next_state":"Pending Submission",
    "allowed":"Warehouse User",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":"action-1",
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Pending Submission",
    "action":"Submit",
    "next_state":"Posted",
    "allowed":"Chief Sales Officer",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {"name":"r170kl8011",
    "owner":"Administrator",
    "creation":"2025-10-29 15:33:17.493710",
    "modified":"2025-10-29 15:33:17.493710",
    "modified_by":"Administrator",
    "docstatus":0,
    "state":"Pending Submission",
    "action":"Submit",
    "next_state":"Posted",
    "allowed":"Sales Supervisor",
    "allow_self_approval":0,
    "send_email_to_creator":0,
    "condition":"frappe.db.get_value(\"Warehouse\", doc.to_warehouse, \"warehouse_user\") == frappe.session.user",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Pending Submission",
    "action":"Reject Submission",
    "next_state":"Rejected Submission",
    "allowed":"Chief Sales Officer",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Pending Submission",
    "action":"Reject Submission",
    "next_state":"Rejected Submission",
    "allowed":"Sales Supervisor",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Rejected Submission",
    "action":"Retrieve",
    "next_state":"Saved",
    "allowed":"Warehouse User",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Posted",
    "action":"Cancel for Review",
    "next_state":"Pending Cancellation",
    "allowed":"Warehouse User",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Pending Cancellation",
    "action":"Cancel",
    "next_state":"Discarded",
    "allowed":"Chief Sales Officer",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":"action-9",
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Pending Cancellation",
    "action":"Cancel",
    "next_state":"Discarded",
    "allowed":"Sales Supervisor",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Pending Cancellation",
    "action":"Reject Cancellation",
    "next_state":"Rejected Cancellation",
    "allowed":"Chief Sales Officer",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Pending Cancellation",
    "action":"Reject Cancellation",
    "next_state":"Rejected Cancellation",
    "allowed":"Sales Supervisor",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"},
    {
    "state":"Rejected Cancellation",
    "action":"Retrieve",
    "next_state":"Posted",
    "allowed":"Warehouse User",
    "allow_self_approval":1,
    "send_email_to_creator":0,
    "condition":"",
    "workflow_builder_id":None,
    "parent":"Stock Transfer Process",
    "parentfield":"transitions",
    "parenttype":"Workflow",
    "doctype":"Workflow Transition"}]}

    try:
        if not frappe.db.exists("Workflow", "Stock Transfer Process"):
            wf = frappe.get_doc(workflow_dict)
            check_for_states_and_transitions(wf)
            wf.insert(ignore_permissions=True)
            print("✅ Created 'Stock Transfer Process' Workflow")
        else:
            print("ℹ️ 'Stock Transfer Process' Workflow already exists")
    except Exception as e:
        print(f"❌ Failed to create 'Stock Transfer Process' Workflow: {e}")

def check_for_states_and_transitions(workflow_dict):
    # Ensure all states exist
    for state in workflow_dict.states:
        if not frappe.db.exists("Workflow State", state.state):
            ws = frappe.get_doc({"workflow_state_name": state.state, "doctype":"Workflow State"})
            ws.insert(ignore_permissions=True)
            print(f"✅ Created Workflow State: {state.state}")

    # Ensure all transitions exist
    for transition in workflow_dict.transitions:
        if not frappe.db.exists("Workflow Action Master", transition.action):
            wt = frappe.get_doc({"doctype":"Workflow Action Master", "workflow_action_name": transition.action})
            wt.insert(ignore_permissions=True)
            print(f"✅ Created Workflow Action Master: {transition.action}")